# Generated by Django 4.0.2 on 2022-02-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_rating_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
