# Generated by Django 4.0.2 on 2022-02-14 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_rating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='averageRating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='ratingCount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
