# Generated by Django 4.0.2 on 2022-02-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_averagerating_post_ratingcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='averageRating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='ratingCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
